### ISSUE TITLE
ImportError: cannot import name 'parse_uri' from 'smart_open' 

### ISSUE THREAD

**Issue by kalenkovich** [kalenkovich/reproduced-MEEG-group-study#17]
Tried to reproduce this branch locally, but after ```snakemake all --cores 1``` it returns an error:

```
Traceback (most recent call last):
  File "E:\Egor_Levchenko\Software\Miniconda\envs\reproduction\lib\site-packages\snakemake\__init__.py", line 593, in snakemake
    workflow.include(
  File "E:\Egor_Levchenko\Software\Miniconda\envs\reproduction\lib\site-packages\snakemake\workflow.py", line 1087, in include
    if is_local_file(snakefile):
  File "E:\Egor_Levchenko\Software\Miniconda\envs\reproduction\lib\site-packages\snakemake\common.py", line 65, in is_local_file
    from smart_open import parse_uri
ImportError: cannot import name 'parse_uri' from 'smart_open' (E:\Egor_Levchenko\Software\Miniconda\envs\reproduction\lib\site-packages\smart_open\__init__.py)
```

I've checked if smart_open is installed and it is with version 1.9.0, but I guess the problem is somewhere else.

Do you have any ideas?

_Originally posted by @levchenkoegor in https://github.com/kalenkovich/reproduced-MEEG-group-study/issues/3#issuecomment-896732340_

**Comment by kalenkovich** [comment]
It looks like snakemake implicitly depends on smart_open version 3. See [this comment](https://github.com/nanoporetech/pipeline-structural-variation/issues/18#issuecomment-806568556).

Install with
```sh
conda install -c conda-forge smart_open=3
```

**Comment by kalenkovich** [comment]
@levchenkoegor, try PR #18
